services:
  medicaloffice:
    build:
      context: .
    container_name: medicaloffice-app
    ports:
      - "${APP_PORT}:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION_TOKEN=${JWT_EXPIRATION_TOKEN}

    networks:
      - medical-network
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: database-postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - medical-network


networks:
  medical-network: